package database

const (
	//Строка с SELECT запросом, который выводит в результат все возможные аварейсы
	SelectAllFlights = `SELECT
	FLIGHT.F_NUMBER,
	FLIGHT.F_TIME,
	AIRLINE.AL_NAME,
	AP1.AP_NAME,
	AP2.AP_NAME,
	C1.C_NAME,
	C2.C_NAME,
	FLIGHT.F_COST
FROM
	FLIGHT
	JOIN AIRLINE 		ON F_AIRLINE_ID	= AL_ID
	JOIN ROUTE 			ON F_ROUTE 		= R_ID
	JOIN AIRPORT AP1 	ON AP1.AP_ID 	= ROUTE.R_AIRPORT_DEPART
	JOIN AIRPORT AP2 	ON AP2.AP_ID 	= ROUTE.R_AIRPORT_DEST
	JOIN CITY C1 		ON C1.C_ID 		= AP1.AP_CITY_ID
	JOIN CITY C2 		ON C2.C_ID 		= AP2.AP_CITY_ID;`

	SelectParamFlights =`SELECT
	FLIGHT.F_NUMBER,
	FLIGHT.F_TIME,
	AIRLINE.AL_NAME,
	AP1.AP_NAME,
	AP2.AP_NAME,
	C1.C_NAME,
	C2.C_NAME,
	FLIGHT.F_COST
FROM
	FLIGHT
	JOIN AIRLINE 		ON F_AIRLINE_ID	= AL_ID
	JOIN ROUTE 			ON F_ROUTE 		= R_ID
	JOIN AIRPORT AP1 	ON AP1.AP_ID 	= ROUTE.R_AIRPORT_DEPART
	JOIN AIRPORT AP2 	ON AP2.AP_ID 	= ROUTE.R_AIRPORT_DEST
	JOIN CITY C1 		ON C1.C_ID 		= AP1.AP_CITY_ID
	JOIN CITY C2 		ON C2.C_ID 		= AP2.AP_CITY_ID
WHERE 
	C1.C_NAME = $1 
	AND C2.C_NAME = $2 
	AND EXTRACT(YEAR FROM FLIGHT.F_TIME) = $3 
	AND EXTRACT(MONTH FROM FLIGHT.F_TIME) = $4
	AND EXTRACT(DAY FROM FLIGHT.F_TIME) = $5;`
)